# Generated by Django 4.2.1 on 2023-05-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('debt', models.IntegerField(verbose_name='Задолженность')),
                ('products', models.ManyToManyField(to='sellers.product', verbose_name='Продукты')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='PrivateBusinessman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(verbose_name='Задолженность')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('products', models.ManyToManyField(to='sellers.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Частный предприниматель',
                'verbose_name_plural': 'Частные предприниматели',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='sellers.product', verbose_name='Продукты'),
        ),
    ]
